<?php

namespace repositories;
use modeles\Role;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return null|Role
     */
    public function getAdminRole()
    {
        return $this->findOneBy(array('id' => 1));
    }

    /**
     * @return null|Role
     */
    public function getEditorRole()
    {
        return $this->findOneBy(array('id' => 2));
    }

    /**
     * @return null|Role
     */
    public function getRegularRole()
    {
        return $this->findOneBy(array('id' => 3));
    }

    /**
     * @return null|Role
     */
    public function getViewerRole()
    {
        return $this->findOneBy(array('id' => 4));
    }
}
